name: linting

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    permissions:
          contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     - name: Lint
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_YAML: true
          VALIDATE_GO: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Install gosec
        run: |
          # Install gosec
          go get github.com/securego/gosec/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...
